version: "3.7"

services:

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111PPpp
      MYSQL_DATABASE: phonebook-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Clarusway-1
    volumes:
      - db-data:/var/lib/mysql
    configs:
      - source: initialdatabase
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet

  appserver:
    image: "${ECR_REGISTRY}/${APP_REPO_NAME}:latest"
    deploy:
      mode: global
    ports:
      - "80:80"
    networks:
      - mynet

volumes:
  db-data:

configs:
  initialdatabase:
    file: ./init.sql

networks:
  mynet:
    driver: overlay
